import re
string = 'Crossin 编程123教室 hi23333.'
result1 = re.findall(r'\d', string)
print (result1)
result1 = re.findall(r'\D', string) #非数字
print (result1)

result2 = re.findall(r'\d+', string)
print (result2)
result3 = re.findall(r'\d?', '1a23')
print (result3)
result4 = re.findall(r'\d*', string)
print (result4)
result5 = re.findall(r'.3', string)
print (result5)
result6 = re.findall(r'.*', string)
print (result6)
result7 = re.findall(r'C.*n', string)
print (result7)
result8 = re.findall(r'C.*3', string)
print (result8)
result9 = re.findall(r'\d{2,6}', string)
print (result9)
result10 = re.findall(r'[23si]+', string)
print (result10)
result10 = re.findall(r'[^23si]+', string)
print (result10)
print ("&&&&&&&&&&&&")
result11 = re.findall(r'[0-9A-z]+', string)
print (result11)
result12 = re.findall(r'[0-9]+|[A-z]+', string)
print (result12)
result13 = re.findall(r'^ss', string)
print (result13)
result14 = re.findall(r'3.$', string)
print (result14)
result15 = re.findall(r'3\.$', string)
print (result15)
result16 = re.findall(r'\w+', string)
print (result16)
result16 = re.findall(r'\W+', string)
print (result16)
print ('***********')
result17 = re.findall(r'.i', string)
print (result17)
result17 = re.findall(r'\b.i', string)
print(result17)
result17 = re.findall(r'\B.i', string)
print(result17)
result17 = re.findall(r'\b.i', 'hi,hi hi')
print(result17)
result18 = re.findall(r'\s.i', 'hi,hi hi') #空白或tab制表符
print (result18)
result18 = re.findall(r'\S.i', 'hi,hi hi') #空白或tab制表符
print (result18)

